session: simple
plugins:
    Auth::Extensible:
        realms:
            ldap:
                provider: LDAP
                server: 127.0.0.1:3333
                basedn: dc=ofosos,dc=org
                userrdn: cn
                userattrs: 'cn dn name userPrincipalName'
                objectClass: user
                rolefilter: memberOf=cn
                grouprdn: cn
                authdn: cn=Administrator
                bindpw: blafasel
                searchbase: cn=users,dc=ofosos,dc=org
                roles: Jever,Warsteiner,Budvar
logger: console
show_errors: 1
